name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy Release
    runs-on: ubuntu-latest
    needs: [release]  # Зависит от успешного завершения release workflow

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download release artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build for deployment
      run: |
        npm run build
        cd src-tauri
        cargo tauri build --release

    # Пример развертывания на GitHub Pages (если нужно)
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/tags/v*'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages

    # Пример развертывания на другие платформы
    - name: Deploy to custom server
      if: github.ref == 'refs/tags/v*' && secrets.DEPLOY_TOKEN
      run: |
        # Здесь можно добавить логику развертывания на ваш сервер
        echo "Deploying to custom server..."
        # rsync -avz artifacts/ user@server:/path/to/deploy/
        # или другие команды развертывания

    - name: Notify deployment
      if: github.ref == 'refs/tags/v*'
      run: |
        echo "Deployment completed for ${{ github.ref_name }}"
        # Здесь можно добавить уведомления (Slack, Discord, etc.)
