name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release for ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Rust dependencies
      run: |
        cd src-tauri
        cargo install tauri-cli --version "^2"

    - name: Build frontend
      run: npm run build

    - name: Build Tauri app
      run: |
        cd src-tauri
        cargo tauri build --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-release
        path: |
          src-tauri/target/release/bundle/
          src-tauri/target/release/*.exe
          src-tauri/target/release/*.app
          src-tauri/target/release/*.dmg
        retention-days: 30

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/ubuntu-latest-release/**/*
          artifacts/windows-latest-release/**/*
          artifacts/macos-latest-release/**/*
        generate_release_notes: true
        draft: false
        prerelease: false
