name: Version Bump

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'src-tauri/**'
      - 'package.json'
      - 'src-tauri/Cargo.toml'

jobs:
  version-bump:
    name: Bump Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Get current version
      id: current-version
      run: |
        cd src-tauri
        echo "version=$(cargo metadata --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT

    - name: Check if version bump is needed
      id: check-bump
      run: |
        if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "bump-needed=true" >> $GITHUB_OUTPUT
        else
          echo "bump-needed=false" >> $GITHUB_OUTPUT
        fi

    - name: Bump version
      if: steps.check-bump.outputs.bump-needed == 'true'
      run: |
        # Bump patch version
        cd src-tauri
        cargo set-version --bump patch
        
        # Update package.json version to match
        cd ..
        npm version patch --no-git-tag-version
        
        # Get new version
        NEW_VERSION=$(cd src-tauri && cargo metadata --format-version 1 | jq -r '.packages[0].version')
        echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: steps.check-bump.outputs.bump-needed == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: bump version to ${{ steps.current-version.outputs.version }}'
        title: 'chore: bump version to ${{ steps.current-version.outputs.version }}'
        body: |
          Автоматическое обновление версии
          
          - Обновлена версия в Cargo.toml
          - Обновлена версия в package.json
          
          Версия: ${{ steps.current-version.outputs.version }}
        branch: version-bump-${{ steps.current-version.outputs.version }}
        delete-branch: true
